spring.application.name=ApiGateway
server.port=8084


# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register Gateway with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Gateway routes
spring.cloud.gateway.routes[0].id=HotelService
spring.cloud.gateway.routes[0].uri=lb://HotelService
spring.cloud.gateway.routes[0].predicates[0]=Path=/hotels/**,/staffs/**

spring.cloud.gateway.routes[1].id=RatingService
spring.cloud.gateway.routes[1].uri=lb://RatingService
spring.cloud.gateway.routes[1].predicates[0]=Path=/ratings/**

spring.cloud.gateway.routes[2].id=UserService
spring.cloud.gateway.routes[2].uri=lb://UserService
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/**

# Enable debug logging for Spring Cloud Gateway
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.server=DEBUG
