

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingservice
    username: postgres
    password: Sadhna@123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    